package com.selectica.Base.querydsl;

import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.types.Path;
import com.mysema.query.types.PathMetadata;
import com.mysema.query.types.path.DateTimePath;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;
import com.selectica.spring.domain.querydsl.QSBobject;
import com.selectica.spring.domain.querydsl.QSDictValue;

import javax.annotation.Generated;
import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;


/**
 * QDGeneralclausereference is a Querydsl query type for QDGeneralclausereference
 */
@Generated("com.mysema.query.sql.codegen.MetaDataSerializer")
public class QDGeneralclausereference extends com.mysema.query.sql.RelationalPathBase<QDGeneralclausereference> {

    private static final long serialVersionUID = 1078997159;

    public static final QDGeneralclausereference dGeneralclausereference = new QDGeneralclausereference("D_GENERALCLAUSEREFERENCE");

    public final NumberPath<Integer> clausename = createNumber("clausename", Integer.class);

    public final NumberPath<Integer> clauserisklevel = createNumber("clauserisklevel", Integer.class);

    public final StringPath clauseshortname = createString("clauseshortname");

    public final StringPath sysautogenerated = createString("sysautogenerated");

    public final NumberPath<Integer> sysBobjectid = createNumber("sysBobjectid", Integer.class);

    public final DateTimePath<java.util.Date> sysCreatedtm = createDateTime("sysCreatedtm", java.util.Date.class);

    public final StringPath sysCreateevent = createString("sysCreateevent");

    public final NumberPath<Integer> sysCuserid = createNumber("sysCuserid", Integer.class);

    public final NumberPath<Integer> sysDataexmversion = createNumber("sysDataexmversion", Integer.class);

    public final StringPath sysDatedefpath = createString("sysDatedefpath");

    public final NumberPath<Integer> sysId = createNumber("sysId", Integer.class);

    public final DateTimePath<java.util.Date> sysModifydtm = createDateTime("sysModifydtm", java.util.Date.class);

    public final NumberPath<Integer> sysMuserid = createNumber("sysMuserid", Integer.class);

    public final NumberPath<Integer> sysParentid = createNumber("sysParentid", Integer.class);

    public final StringPath sysParenttablename = createString("sysParenttablename");

    public final NumberPath<Integer> sysSource = createNumber("sysSource", Integer.class);

    public final NumberPath<Integer> sysStatus = createNumber("sysStatus", Integer.class);

    public final com.mysema.query.sql.PrimaryKey<QDGeneralclausereference> dGeneralclausereference24Pk = createPrimaryKey(sysId);

//    public final com.mysema.query.sql.ForeignKey<QSBobject> dGeneralcla24SysParentidFk = createForeignKey(sysParentid, "ID");

    public final com.mysema.query.sql.ForeignKey<QSBobject> dGeneralcl24SysBobjectidFk = createForeignKey(sysBobjectid, "ID");

    public final com.mysema.query.sql.ForeignKey<QSDictValue> dGeneral24ClauserisklevelFk = createForeignKey(clauserisklevel, "ID");

    public final com.mysema.query.sql.ForeignKey<QSDictValue> dGeneralclaus24ClausenameFk = createForeignKey(clausename, "ID");

    public QDGeneralclausereference(String variable) {
        super(QDGeneralclausereference.class, forVariable(variable), "VZAKHARCHENKO", "D_GENERALCLAUSEREFERENCE");
        addMetadata();
    }

    public QDGeneralclausereference(String variable, String schema, String table) {
        super(QDGeneralclausereference.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public QDGeneralclausereference(Path<? extends QDGeneralclausereference> path) {
        super(path.getType(), path.getMetadata(), "VZAKHARCHENKO", "D_GENERALCLAUSEREFERENCE");
        addMetadata();
    }

    public QDGeneralclausereference(PathMetadata<?> metadata) {
        super(QDGeneralclausereference.class, metadata, "VZAKHARCHENKO", "D_GENERALCLAUSEREFERENCE");
        addMetadata();
    }

    public void addMetadata() {
        addMetadata(clausename, ColumnMetadata.named("CLAUSENAME").withIndex(2).ofType(Types.DECIMAL).withSize(18).notNull());
        addMetadata(clauserisklevel, ColumnMetadata.named("CLAUSERISKLEVEL").withIndex(4).ofType(Types.DECIMAL).withSize(18));
        addMetadata(clauseshortname, ColumnMetadata.named("CLAUSESHORTNAME").withIndex(3).ofType(Types.VARCHAR).withSize(18));
        addMetadata(sysautogenerated, ColumnMetadata.named("SYSAUTOGENERATED").withIndex(1).ofType(Types.VARCHAR).withSize(1));
        addMetadata(sysBobjectid, ColumnMetadata.named("SYS_BOBJECTID").withIndex(6).ofType(Types.DECIMAL).withSize(18).notNull());
        addMetadata(sysCreatedtm, ColumnMetadata.named("SYS_CREATEDTM").withIndex(14).ofType(Types.TIMESTAMP).withSize(11).withDigits(6));
        addMetadata(sysCreateevent, ColumnMetadata.named("SYS_CREATEEVENT").withIndex(12).ofType(Types.VARCHAR).withSize(32));
        addMetadata(sysCuserid, ColumnMetadata.named("SYS_CUSERID").withIndex(15).ofType(Types.DECIMAL).withSize(18));
        addMetadata(sysDataexmversion, ColumnMetadata.named("SYS_DATAEXMVERSION").withIndex(10).ofType(Types.DECIMAL).withSize(18));
        addMetadata(sysDatedefpath, ColumnMetadata.named("SYS_DATEDEFPATH").withIndex(9).ofType(Types.VARCHAR).withSize(200));
        addMetadata(sysId, ColumnMetadata.named("SYS_ID").withIndex(5).ofType(Types.DECIMAL).withSize(7).notNull());
        addMetadata(sysModifydtm, ColumnMetadata.named("SYS_MODIFYDTM").withIndex(16).ofType(Types.TIMESTAMP).withSize(11).withDigits(6));
        addMetadata(sysMuserid, ColumnMetadata.named("SYS_MUSERID").withIndex(17).ofType(Types.DECIMAL).withSize(18));
        addMetadata(sysParentid, ColumnMetadata.named("SYS_PARENTID").withIndex(7).ofType(Types.DECIMAL).withSize(18).notNull());
        addMetadata(sysParenttablename, ColumnMetadata.named("SYS_PARENTTABLENAME").withIndex(8).ofType(Types.VARCHAR).withSize(32).notNull());
        addMetadata(sysSource, ColumnMetadata.named("SYS_SOURCE").withIndex(11).ofType(Types.DECIMAL).withSize(18));
        addMetadata(sysStatus, ColumnMetadata.named("SYS_STATUS").withIndex(13).ofType(Types.DECIMAL).withSize(18));
    }

}

